### ISSUE TITLE
Translation bug in the text section

### ISSUE THREAD

**Issue by ppxasjsm** [IMAGINARY/imaginary-web#100]
I have noticed there is some bits of Turkish on the English welcome page of the text section. I have attached a screenshot. 
![screenshot from 2015-09-01 10 18 17](https://cloud.githubusercontent.com/assets/3668316/9600468/2255cf5c-5093-11e5-9183-59089f93edea.png)

**Comment by HexeBianca** [comment]
I fixed it. 
Will ask Ferit to double check, before I close the issue.
