### ISSUE TITLE
Off-site backup in Amazon S3

### ISSUE THREAD

**Issue by elondaits** [IMAGINARY/imaginary-web#104]
As an incremental improvement and experiment Amazon S3 cloud storage can be used for storing an off-site backup. An Amazon AWS account has to be created.

**Comment by elondaits** [comment]
I installed AWS CLI tools on the hosting server which can be used to sync the Imaginary files to an S3 backup.

**Comment by andreasdanielmatt** [comment]
we already have an account at AWS (we registered it once, when we planned to use some of their services). I can get any package or service for that account? What do we need? Do you have PGP (I can send you the passwds)?

**Comment by elondaits** [comment]
I sent my public key.

**Comment by elondaits** [comment]
I've set it up and are currently uploading all user files to a private backup bucket.

**Comment by elondaits** [comment]
Scripts have been installed for syncing user files to an Amazon S3 bucket and copying all database backups to another bucket.
These scripts are described in the Backup Policy Google Doc.
