### ISSUE TITLE
untranslatable phrase in detailed snapshots view

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#108]
The phrase: 'If you are interested in translating this snapshot, please contact us at info@imaginary.org' seems to be not translatable.
It is used below the abstract of a snapshot in the detailed view of a single snapshot.
Example: http://imaginary.org/de/node/596

**Comment by elondaits** [comment]
¿Can you give me the german translation so I can add it right away? I'll add the others as pending in the spreadsheet.

**Comment by HexeBianca** [comment]
It depends on the decisiion about using the formal or informal version (see #107 ).

**Comment by elondaits** [comment]
OK. If I get it today I'll try to add it right away so it's in place for tomorrow's launch.

**Comment by HexeBianca** [comment]
Then let's use the formal version for now. This would be in German:
"Falls Sie diesen Schnappschuss übersetzen möchten, kontaktieren Sie uns bitte über info@imaginary.org."

**Comment by elondaits** [comment]
I made the item translatable and added translations for German and Spanish. The rest are pending in the spreadsheet (along with some others that were recently added).
