### ISSUE TITLE
Junior and senior editors are not displayed

### ISSUE THREAD

**Issue by ppxasjsm** [IMAGINARY/imaginary-web#112]
In the snapshots, junior and senior editor names are not displayed when you are not logged into the IMAGINARY website:
![loggedout](https://cloud.githubusercontent.com/assets/3668316/11241043/56d7de52-8def-11e5-89f6-5582704bda7e.png)
They are displayed, when logged in.
![logged_in](https://cloud.githubusercontent.com/assets/3668316/11241044/58a51b8c-8def-11e5-996f-464d2d21773f.png)
Can the editors always be shown please.

**Comment by elondaits** [comment]
Done.

The fields needed to be made visibile to Anonymous / Authorized users in the field settings (/admin/structure/types/manage/snapshot/fields)
