### ISSUE TITLE
Link licenses to actual license text or license overview pages

### ISSUE THREAD

**Issue by porst17** [IMAGINARY/imaginary-web#113]
Each license in the license section of a program, gallery, etc. should be a link to the actual license text, or, even better in my opinion, to an overview web site which lists the permissions and responsibilities of the license holder.

Please implement the facilities for the linking.

@andreasdanielmatt Below we should list the external licenses and license summary websites we want to link to.

**Comment by porst17** [comment]
Overwiew sites:
http://choosealicense.com/ resp. http://choosealicense.com/licenses/
https://tldrlegal.com/
http://creativecommons.org/licenses/ and it's sub-sites like http://creativecommons.org/licenses/by/4.0/

A nice thing of the overview sites is that they also provide the full license text.

**Comment by elondaits** [comment]
I implemented it already and deployed it for Programs. I still have to modify the views of other content types for activating the link. I'll close the issue when I do.

The licenses are linked to external sites. I used tldrlegal whenever I could (one or two licenses weren't there) except for CC licenses which have a good overview and comparison in their official site. 

The URLs of the overview pages for each license are configurable through a new field in the same administrative panel used to add or remove licenses. This means it's easy to change the pages used in the future or configure new ones when licenses are added to the site.

**Comment by porst17** [comment]
Great job! Which licenses are missing on http://tldrlegal.com? Maybe they are just listed under a different name (the BSD licensed have several names).

**Comment by HexeBianca** [comment]
For CC-licenses we also have this road map to help the user decide, which one to choose:
https://docs.google.com/drawings/d/1wAMbeADBWgy5VDb4PQL7XSgeGep44Jd_B0hifgOrWaQ/edit
Can this be integrated somehow (maybe only for galleries)?
Not sure if a link to google doc is a good thing to do. Probably better to save it as PDF, put it on the platform directly as file and link to it from the licenses edit tab.

**Comment by porst17** [comment]
@HexeBianca I think this is a separate issue. Here we are talking about links that help visitors to understand the license implications when they want to use the material. Your diagram is to guide authors towards a decision for a license.

**Comment by elondaits** [comment]
The one that wasn't in TLDRLegal is "Clear BSD", which is based on the BSD-3 clause license but with the following text added to the last paragraph:

> NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. 

Another case was "Public Domain", which is not an actual license and thus can't be associated with any license text, not even CC-0. I linked that to Wikipedia's definition of Public Domain.

As for the roadmap: Shouldn't Imaginary try to lead authors to a license that allows derivatives and commercial use unless they're unable or feel very strongly about some other choice? The derivative aspect is important to allow for translations / localization of exhibits and commercial use is important because in some cases it applies even to non-profits.

**Comment by HexeBianca** [comment]
for the road map I opened a new issue #120 .

**Comment by elondaits** [comment]
I deployed the change for the remaining content types (Films, Galleries, Hands-on, both types of text). Let me know if you see a license that should be a link but isn't somewhere... I might have missed a view.
