### ISSUE TITLE
Translations of snapshots

### ISSUE THREAD

**Issue by ppxasjsm** [IMAGINARY/imaginary-web#118]
It seems there is a problem with the translations on the website for snapshots. 
I am only able to upload one pdf for all languages. Obviously I would like to have a pdf for each language of the snapshots. 
So now if I translate for example this snapshots: http://imaginary.org/de/snapshot/billard-und-ebene-flaechen, I still only see the English version, but If I upload a German version of the text, then it is also shown in the English. 
If you need more clarification let me know.

**Comment by elondaits** [comment]
The PDF field is now translatable. You should be able to change it for any language without affecting the others (until you do you will still see the original PDF). Let me know if you run into any problems, I backed up the database before doing the change.

**Comment by HexeBianca** [comment]
Please also enable the file view for downloads below the PDF view. It should work the same as for the general background material, see here for an example:
http://imaginary.org/background-material/katzengold-pyrite-plato-and-a-polynomial
there might be translations of a snapshot into a language other than the six languages of the platform.

**Comment by elondaits** [comment]
That's an altogether different data model.

- Snapshots had just one field for the PDF, for all translations.
- I changed it to a translatable field.
- Background Materials has a field for a PDF alongside a language field which is separate from the translation system. This is why even if there's a german PDF you still only see the english one in the viewer. (Andreas mentioned this issue somewhere, but I can't find it).

To change Snapshots to the way Background Materials works I *THINK* I'll have to manually edit all snapshots to move PDFs from the current field to a new other... but they'll work like BG Materials do now: the viewer always shows the default.

... So, it'd be possible to have a combination of both that works right, but it's not a quick / easy change... I'll create a new issue for it.

**Comment by elondaits** [comment]
I created issue #119 with these requests.

**Comment by HexeBianca** [comment]
Just for info:
I have seen the file view for the snapshots before. It just did not have the language associated to it.
