### ISSUE TITLE
relation not shown

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#127]
I added a relation between a gallery and an event. It is neither shown at the event page nor at the gallery.
http://imaginary.org/gallery/hiltrud-heinrich-fractals
http://imaginary.org/event/strange-worlds

**Comment by elondaits** [comment]
The relation "is gallery of" is not displayed, but "is exhibit of event/exhibition" is. I added it and it's being shown in both the gallery and event. This, apparently, is the by-design behavior. I assume "is gallery of" is used for programs or other cases. Is it OK?

**Comment by HexeBianca** [comment]
great, thank you.
