### ISSUE TITLE
adapt automatic link settings

### ISSUE THREAD

**Issue by woestenfeld** [IMAGINARY/imaginary-web#131]
We should have as standard setting, that an inserted link opens 
a) in same window, if going to any imaginary.org/... page
b) in new window, if going to any outside page.

**Comment by elondaits** [comment]
Opening links in a new windows is discouraged by usability and accessibility guidelines. See for example: 

https://www.smashingmagazine.com/2008/07/should-links-open-in-new-windows/

and

https://www.w3.org/TR/WCAG20-TECHS/G200.html

at one point it was even removed from the HTML standard as a possibility.

**Comment by andreasdanielmatt** [comment]
Thanks Eric for the info, if this is the standard, then we leave it this way!
