### ISSUE TITLE
Clarify BSD-style licenses

### ISSUE THREAD

**Issue by porst17** [IMAGINARY/imaginary-web#138]
Currently, the only BSD license choice is FreeBSD, which is also known as *2-clause BSD license*. However, the most common choice is AFAIK the *3-clause BSD license* and we actually have two programs listed on the platform that are released under the 3-clause license but have the wrong 2-clause license assigned.

I vote for adding the *3-clause BSD license* and renaming the *FreeBSD license* to *2-clause BSD license*.

We could also add the *4-clause BSD license* (also known as the *original BSD license*), but it is considered largely incompatible with other FOSS licenses. Therefore, I think we shouldn't add it.

For clarification of the different versions: https://en.wikipedia.org/wiki/BSD_licenses

**Comment by elondaits** [comment]
According Wikipedia the 3-clause license is also called "Modified BSD", and we have that one although a bit lower on the list. I'll rename and rearrange them.

**Comment by elondaits** [comment]
I changed the license of jReality to 3-clause. I didn't find any other program using a BSD license. It's possible I missed it because programs can have many licenses and I don't know if the methods I used to search capture them all. Let me know and I'll change it.

**Comment by porst17** [comment]
Sorry for the trouble. I missed the *modified BSD license*. 3D-XplorMath is also licensed under the *3-clause BSD license*. I will change it myself.

**Comment by elondaits** [comment]
Still it's better if they're together since they're so closely related and people can always find both. Specially since "FreeBSD" seems like a generic name.
