### ISSUE TITLE
Meta Menu

### ISSUE THREAD

**Issue by christophknoth** [IMAGINARY/imaginary-web#17]
We will add "Users" to the top menu. But this does not work right now as the css has to be updated.

![screenshot 2014-12-11 10 34 08](https://cloud.githubusercontent.com/assets/282518/5391959/6e5cf192-8121-11e4-9738-73279de456cb.png)

**Comment by elondaits** [comment]
Changed in 29a74b4a1c257c39a665050ed0c5d40b3a73777b
