### ISSUE TITLE
no translated titles

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#26]
Below a film or program or other content, there are 'more films' or 'more programs and so on. The title of each of the listed content is always English, even if a different language is chosen, and titles are available in chosen language.

**Comment by elondaits** [comment]
Should be fixed by now in the latest test version (92738bb94f190f9af7f9b5ed6498ff1cdcce611a).

**Comment by HexeBianca** [comment]
great :-)
