### ISSUE TITLE
main buttons link only to english pages

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#28]
When clicking one of the main buttons (programs, galleries...) of the start page in a language other than English, the new page should be shown in the corresponding language. So far, they always link to an English page.
![1](https://cloud.githubusercontent.com/assets/10153723/5612603/14cb7dd6-94d8-11e4-9a24-e6d0af81274c.jpg)

**Comment by christophknoth** [comment]
I guess we should make a sortable view out of it?

**Comment by elondaits** [comment]
I've already fixed this as-is in the korean-compatible version I'm uploading for test this week. I haven't closed the issue yet because I haven't commited the changes.

**Comment by elondaits** [comment]
The text was made translatable in ee9f89fb81e323b2aeead3e9ae24e91f5871e5c9

The links were made to point to the right language in d515fc0d54873323bc9db64ce27b4f2ce22727f5

**Comment by HexeBianca** [comment]
perfect.
