### ISSUE TITLE
Untranslated buttons when editing the webpage

### ISSUE THREAD

**Issue by ppxasjsm** [IMAGINARY/imaginary-web#31]
I noticed that when a language is edited, e.g. Spanish there is no Spanish button for unpublished (retirar). It is the same for Korean, where there is only a Korean button for save and everything else is still English. There may be more of these untranslated buttons.

**Comment by elondaits** [comment]
Do you refer to the forms for editing and translating content (i.e. the back-end)?

If so, part of the interface is translated by Drupal (the site's engine) which provides its own translations for generic functionality. I don't think any work has been done yet to translate the content editing interface and I'm sure there are a lot of missing translations.

I'm not sure what the priority of this would be, as it surely is a lot of work... it would include translating any error/success messages as well.

**Comment by ppxasjsm** [comment]
yes I am talking about the backend. No it definitely is not high priority, but I just wanted to make sure it was recorded somewhere, while I noticed it.

**Comment by ppxasjsm** [comment]
Safely ignore it for the current milestone and see it more as an enhancement I would say. People who upload things on the platform usually speak english I would guess.

**Comment by elondaits** [comment]
I'm closing this issue because as the current policy is not to translate the editing interface (yet) there's no way I can act on this item... and it's better that all issues are actionable. Translating the editing interface should be a full sized project at some point, if it's decided to tackle it.

**Comment by HexeBianca** [comment]
yes, you are right, Eric.
