### ISSUE TITLE
Links are not openable on iPhone/ipads.

### ISSUE THREAD

**Issue by ppxasjsm** [IMAGINARY/imaginary-web#33]
I cannot open (they are clickable) internal links on the website, when viewing with safari browser on iPhone 4s/5s using iOS 8.1.2.
On Android this issues does not seem to occur on the devices I have tried.

**Comment by christophknoth** [comment]
We removed the function that a only a mouse-move makes all links green. They are now green by default. This should fix this issues.

**Comment by HexeBianca** [comment]
@ppxasjsm please test if it works now. Thank you.
