### ISSUE TITLE
renaming of pane word related exhibits for exhibitions

### ISSUE THREAD

**Issue by ppxasjsm** [IMAGINARY/imaginary-web#34]
The pane word **related exhibits** in the exhibitions section (IMAGINARY and mpe exhibition) is a bit confusing in this section, because they are not related, but the actual exhibits of the exhibition.  We discussed with Bianca, Andreas and Daniel, that a better pane word would be **available exhibits**.

**Comment by elondaits** [comment]
@HexeBianca I added "Available exhibits" to the Pane Words Translations spreadsheet and marked it in red. As soon as I have the translations I can see about changing this.

**Comment by elondaits** [comment]
We just got the translations for this so I was able to change it. Done.
