### ISSUE TITLE
Revisions Button

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#39]
It would be great to have a revisions button for all conent types.

**Comment by christophknoth** [comment]
I went through all content types and the revisions are enabled everywhere. So in theory they should work. Where are they exactly missing?

**Comment by HexeBianca** [comment]
I noticed projects and news.

**Comment by christophknoth** [comment]
Ok, found the right place to turn revisions on for those missing content types. From now on they should be generated on all content types we have.

**Comment by HexeBianca** [comment]
great.
