### ISSUE TITLE
display of links to websites

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#41]
Within the programs, the link to an external website is shown directly, not using the title given.
![1](https://cloud.githubusercontent.com/assets/10153723/6315927/8392ac26-ba12-11e4-9c88-2bbe83cb93e7.jpg)
![2](https://cloud.githubusercontent.com/assets/10153723/6315936/a672a4d0-ba12-11e4-8451-08882e92853a.jpg)

**Comment by christophknoth** [comment]
Fixed.

**Comment by HexeBianca** [comment]
great, thank you.
