### ISSUE TITLE
default event

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#43]
In the event calendar, the default event shown, when the calendar is opened (and at the front page) should not be the one farthest in the future but the next one coming up.

**Comment by HexeBianca** [comment]
At the front page in the lower right (next to the news messages) there are still the events in the very future shown. Please change the behavior here as well. Thank you.

**Comment by elondaits** [comment]
I changed it to show the next 3 upcoming events.
