### ISSUE TITLE
different height for the two exhibitions

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#45]
At the front page and here:
http://imaginary.org/exhibitions
The two exhibitions are shown next to each other.
![1](https://cloud.githubusercontent.com/assets/10153723/6534818/b3b89464-c440-11e4-96f2-f484125cfbaa.jpg)
The space for MPE is smaller than for IMAGINARY, maybe because of the shorter title.
May be this can be adjusted by changing the size of the logo?

**Comment by elondaits** [comment]
Take into consideration that if those titles are translated the 3 lines / 2 lines relation in the lengths of the titles might be lost. An alternative would be to just align the images without changing their height.

**Comment by HexeBianca** [comment]
Thanks Eric. A solution which works for all languages would be great.
(I am not sure, if the logos have the same height, this should be checked.)

**Comment by christophknoth** [comment]
I think it is totally fine how it is. If you want to adjust it visually just give the Zitrus more whitespace in the uploaded image.

**Comment by HexeBianca** [comment]
Can we just take out the lines below the logos?

**Comment by christophknoth** [comment]
Why?

**Comment by HexeBianca** [comment]
because they are on different levels, which looks wrong. This was the whole point of this issue.

**Comment by HexeBianca** [comment]
It is of very low priority, so we can talk about it when changing the layout of the front page, eventually.

**Comment by christophknoth** [comment]
Everything is on different levels if it has different length. If you really want to change it change the size of the headline or the size of the images. But this is just naturally the internet I do not think there is anything wrong with this particular page of imaginary.
