### ISSUE TITLE
The contact form fields are not translated

### ISSUE THREAD

**Issue by elondaits** [IMAGINARY/imaginary-web#47]
The fields in the contact form are not being translated. The contact form is implemented through the Webform module which by default doesn't attempt to translate its fields. There's a "Webform Localization" module that allows translation through i18n strings, which might be a good alternative.

**Comment by christophknoth** [comment]
I am curious if those forms are really used and if we really need them?

**Comment by HexeBianca** [comment]
I would definitely keep them. Users should be able to contact each other, we are an open platform and exchange is very welcome.

**Comment by elondaits** [comment]
The contact form this issue refers to is this one:

http://imaginary.org/contact

... that is, the form to contact Imaginary, which is "central" site
functionality. We didn't get to any back end features yet, as the full
internationalization of the front end is not finished yet.

**Comment by HexeBianca** [comment]
Oh, we need this one!!!

**Comment by christophknoth** [comment]
(y)

**Comment by christophknoth** [comment]
:thumbsup:

**Comment by elondaits** [comment]
Fixed in 15acf57c84e26e84034be5984c6f64fa820d38e0 . Also added a new page in the Pane Words spreadsheet (translations were already done). Will deploy soon.
