### ISSUE TITLE
redesign of the front page

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#50]
find a way to implement links at the front page to:
latest newsletter (done)
project overview page (done)
blog overview

discuss a new layout with the team:
Antonia and Bianca agree to remove the big full-width sapce for the last event as well as to remove the big image rotator at the top, which will lead to more information at first sight.
Gert-Martin's suggestions are:
" I would also prefer a different timeline with the option to jump back year by year, and I like to see Twiter and Facebook at the top"

**Comment by konrad-renner** [comment]
On the sidebar, there now is a link to the latest newsletter, below the step-guide?
Do we still need this step-guide?

Any ideas where the projects button should be visible? I'm thinking about the top menu like »About Participate and Contact«. Would that makes sense to you?

**Comment by christophknoth** [comment]
I think the rotating top image is quite important for the visual identity of the Imaginary website. And the buttons are actually just an explanation of the menu so I am not sure if they really need to be up higher. But if there is a big consent about disabling the rotating top images we could disable them for a test period.

**Comment by HexeBianca** [comment]
I think, we don't need the step guide. However, if it is gone, we need a link to the projects page. Could one of the big buttons lead to projects? The goal is to have more than six buttons available and to only show six, right?

**Comment by HexeBianca** [comment]
If we keep the rotating top image, how about giving it some interactive use? Could it be made clickable? Each image could be a big button, so we wouldn't need the six buttons below?
One of the rotating images could show the text "IMAGINARY is your place for open and interactive mathematics. Join a worldwide community of math enthusiasts!" which would save even more space.
I think we need to save space at the front page. Ideas welcome!

**Comment by elondaits** [comment]
Regarding the six "big buttons": There are currently eight of them, but only six are chosen randomly and shown. It's not a good place for options that should be always available. It's useful for promoting parts of the site, but bad for standard navigation.

**Comment by HexeBianca** [comment]
I agree, the buttons should not be used for standard navigation.
Where would be a good place for the link to the projects page?

**Comment by HexeBianca** [comment]
I wouldn't put a projects link in the top menu, Konrad.
We can discuss putting the Exhibitions link there, and then there would be some space for the projects link in the general menu.

**Comment by christophknoth** [comment]
I think there is space for two or three more small grey links. Projects, Users could be there.

**Comment by elondaits** [comment]
The Users link is already visible in dev_eric.imaginary.org (*user* dev,
*pass* kjaTe4Q9YRI9), which is the version that will go live on friday.
There is space for one more link but it's getting crowded in some
languages... spanish for instance.

**Comment by christophknoth** [comment]
Ok, then only one more :)

**Comment by danielramosg** [comment]
Hi, I just "discovered" the Issues tracking on our github a few days ago. I like the general aesthetics of the web in general and I respect the designers role, but given that this is an open Issue and "help wanted":

* I don't like the rotating prism. I feel tense each time it rotates suddenly. Besides, it displays five images but geometrically it has four sides, which makes it more disturbing to me. The old fading transitions we had were much more peaceful and pleasant, I would restore them.
* The text "IMAGINARY is your place..." is too big, and the serif font seems out of place. Honestly, it looks like some css broke and it fell back to plain html in this sentence. I would put it in our standard Futura sans serif font and smaller, occupying just one line.
* The big buttons are really beautiful. It's a pitty that they are not more visible and used. Indeed the navigation function is duplicated, and I would prefer to disable the menu bar and keep the big buttons.

My proposed view:
On the top of the page the current "About, Users, ...", then the IMAGINARY logo and then the fading images replacing the rolling prism. Then the sentence "... is your place..."  more discrete, and below the six buttons. On the right of the buttons, an arrow/triangle that allows to slide them and unveil more buttons (this was already suggested, I think). The navigation from the main page is then done by the buttons, and in all the other pages we keep the more minimalistic menu bar. This can fit well in a normal desktop screen. Scrolling, the events and news are fine, in a more blog/news-site style. Further, navigation from main page through sliding buttons allows to put more buttons, like Projects, Events... that do not need to be available in the text menu afterwards.

That's just "in my humble opinion",

D.

**Comment by elondaits** [comment]
I'm closing this because a redesign of the home page is under way.
