### ISSUE TITLE
Projects - button?

### ISSUE THREAD

**Issue by ppxasjsm** [IMAGINARY/imaginary-web#51]
So the website has a feature called projects, which contains all sorts of useful information regarding an ongoing project such as Imaginary Israel or Matie or Turkey. However it is basically only findable if you know about it and have the direct url. I think Gert-Martin already mentioned that this is not ideal. Is there an easy way to incorporate a project button somewhere that will allow to reach the projects overview page?

**Comment by HexeBianca** [comment]
See also: https://github.com/IMAGINARY/imaginary-web/issues/46
