### ISSUE TITLE
Titles in some listings are not translated

### ISSUE THREAD

**Issue by elondaits** [IMAGINARY/imaginary-web#58]
Content listings such as <http://imaginary.org/es/galleries> and <http://imaginary.org/es/physical-exhibits> show the titles of nodes in english, even though they have translations. The "films" list (<http://imaginary.org/es/films>) does translate titles... editing that view I see there are content:Title and a content:Título fields (Título being Title in spanish). This has to be fixed / normalized across all views.

**Comment by HexeBianca** [comment]
I am just adding German translations to the hands-on modules: the same behaviour here.
http://imaginary.org/de/physical-exhibits

**Comment by christophknoth** [comment]
Fixed.
