### ISSUE TITLE
problems on iPhone and iPad

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#63]
A user reports:
Is the website supported under Apple? iPhone and iPad? I have serious problems, e.g. I cannot login, it is vey, very slow, etc.

**Comment by konrad-renner** [comment]
The website can be viewed on mobile device, but there is no special mobile version/design/template. We know that since we built the site! To do that, we have to redesign the whole website, which is a much heavier milestone.
So, this is not a bug actually!

**Comment by elondaits** [comment]
I think the login problem is fixable... But it's likely slow because of the
large amount of scripts and large images.

**Comment by elondaits** [comment]
Fix in progress in #121
