### ISSUE TITLE
museums map

### ISSUE THREAD

**Issue by danielramosg** [IMAGINARY/imaginary-web#65]
We have a map of math museums, that used to be available at 
http://math-communication-network.imaginary.org/
We link to this map via iframe in
http://imaginary.org/content/math-communication-network
and also in other projects.

It is no longer active, the first link redirects to the main page of imaginary. The code for the map is on the server folder
math-communication-network.imaginary.org/var/www/clients/client2/web19/web/js

please restore the link/server config.

**Comment by elondaits** [comment]
Actually all imaginary subdomains are pointed to the main site. I'm looking around but I don't know why yet.

**Comment by elondaits** [comment]
It's back online. It seems it was some sort of configuration hiccup because all it took to fix it was a re-save of the server configuration with no changes and a web server restart.
