### ISSUE TITLE
wrong status for unpublished content

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#68]
When translating an unpublished news, the status shows 'Published' even though it is not published yet.
![1](https://cloud.githubusercontent.com/assets/10153723/7122430/9d6774b6-e21b-11e4-964e-e288bf20f290.jpg)

**Comment by elondaits** [comment]
That refers to the status of the translation... not the article itself. Check the "translation" tab in the editing form, you'll see a field that says 

**This translation is published**
An unpublished translation will not be visible for non-administrators.

If you turn that off you'll see the status column change to "Not Published".
