### ISSUE TITLE
fake user accounts

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#69]
There is at least one fake user account:
http://imaginary.org/users/bedworks-bedding

Christoph please create a list showing all user accounts which use links within their descriptions. I will then go through the list and delete the fake accounts (as just discussed via skype).

**Comment by christophknoth** [comment]
This view shows all users that have an about me text: http://imaginary.org/dev-users sorted by newest.

**Comment by HexeBianca** [comment]
great, thanks @christophknoth.
