### ISSUE TITLE
Old versions of the timelinejs library force images to load through http

### ISSUE THREAD

**Issue by elondaits** [IMAGINARY/imaginary-web#70]
As part of the efforts to make the Imaginary site load in https without any "insecure content" (content loaded through http) I found that the timelinejs library forces the images it displays through http by doing a search & replace on the URL. 

This was fixed on v2.34.0 of the timelineJS library. Using this version requires updating the views_timelinejs Drupal module which integrates the library into the site. The latest version of the module (beta) only claims compatibility with v2.26, so the update should be throughly tested.

@christophknoth , I know the timelinejs is used in the home page and the main "Events" page. Are there any other pages I should test to see if anything broke?

**Comment by christophknoth** [comment]
These are the only two pages where timeline.js appears. I remember though that we had to change something inside of the library because the the date formats were to long. But maybe this is already different in the current version. Could you paste a screenshot from both versions?

**Comment by elondaits** [comment]
Here are both versions. The only difference seems to be that the date of the previous / next event is printed over the title under the arrows on the sides... which seems useful.

**Old version**
![events-before-2](https://cloud.githubusercontent.com/assets/6472073/7551723/32548656-f66a-11e4-9937-6650a5aa5205.png)

**New version**
![events-after-2](https://cloud.githubusercontent.com/assets/6472073/7551725/3e263e20-f66a-11e4-9d04-a717a2e0dfc9.png)

This new version of the module also uses image styles, which allows to shrink the images (through Drupal Image Styles) before showing them in the timeline... that should have a big impact in the size of the pages.

**Comment by elondaits** [comment]
@christophknoth Is it OK? I'll most likely will be deploying this change soon.

**Comment by christophknoth** [comment]
Oh sorry, did not see this. I think for maintainability it is easier to leave the dates in but I think we removed them before.

**Comment by elondaits** [comment]
Fixed on abc88ec56abf3dc1b65347b64449bad38c578c37
Will deploy soon.
