### ISSUE TITLE
Project status not translated

### ISSUE THREAD

**Issue by elondaits** [IMAGINARY/imaginary-web#75]
The status of projects in the Project section is not being translated. Also, the "Supported by" and "Partners / Sponsors" labels in the detail view of projects are not being translated either.

**Comment by HexeBianca** [comment]
Just to understand, how you use github:
Will this stay as you described or did you fix it?
 
All the best
Bianca


  _____

**Comment by elondaits** [comment]
Yes, I fixed it... It is currently fixed in my development environment but not yet deployed. It'll be deployed along with other issues

I normally would mark the git commit where the issue is fixed, but in this case the change is only in the "Pane words" spreadsheet and the Drupal configuration... no code changes were needed.

I'm not totally sure how to best document a case such as this, but whatever issue I close without a fix will be marked with the "wontfix" label and an explanation.
