### ISSUE TITLE
[Snapshots] setting DOI

### ISSUE THREAD

**Issue by ppxasjsm** [IMAGINARY/imaginary-web#77]
Hi, a couple of the DOI's in the snapshot section are wrong. It is not clear to me how to change that and does not seem to be part of any of the obvious edit tabs of a snapshot.

**Comment by andreasdanielmatt** [comment]
the DOI number is automatically built from the number and date. Christoph would need to add a new option for DE and EN - or maybe even easier, a field, where one can fill in the complete DOI (depends on Christoph). If you do it automatically, there will always be a syntax-correct DOI.
