### ISSUE TITLE
display image depending on selected language

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#78]
Is it possible to show different versions of the MPE-image, depending on the chosen language on the platform?
http://imaginary.org/exhibition/mathematics-of-planet-earth

**Comment by christophknoth** [comment]
Galleries can not be translated and I am not sure if we should change that as it could be very confusing. As a workaround you could try to add the image to the text block in the same way as we are adding images to the newsletter. Maybe we should try this on a testserver first as I have no idea how it will look.

**Comment by elondaits** [comment]
It's not a good idea to make galleries translatable. When you first translate an existing gallery all photos are copied to the translation, but afterwards each time you add a new picture it has to be added independently to each translation (same for removals).
