### ISSUE TITLE
New licences:

### ISSUE THREAD

**Issue by konrad-renner** [IMAGINARY/imaginary-web#79]
Add new licences to the list.
We will need CC-BY-SA-4.0 (recommended), CC-BY-ND-4.0, CC-BY-NC-SA-4.0 especially for the single snapshots.

**Comment by HexeBianca** [comment]
The new snapshot-template was released today, which offers the new licenses. Therefore, we will soon need them at the platform.

**Comment by konrad-renner** [comment]
New licences are added.
In the content type mask, some licences are display: none; in the css. :)
This has to be changed to the 4.0 version
@christophknoth

**Comment by elondaits** [comment]
I can do that... I have some changes to deploy anyway.

**Comment by christophknoth** [comment]
Ok, cool, because I tried getting my dev version to the latest version but had problems importing the database backup.

**Comment by elondaits** [comment]
Fixed in 20d31e2a84f699aebaf9efaecb16c81830776a55

**Comment by andreasdanielmatt** [comment]
I just tested the visibility of the new licenses (all licenses) and in the snapshot section they do not appear, see: http://imaginary.org/node/add/snapshot (and click on "License/Finish" Tab). Did some of you (Konrad, Christoph, Eric) edit the CSS file in the right way (undo the "non-display" at certain licenses?).

At the other content types it works (all licenses are shown, for example at program) - but there was no "hidden" license in these types. We can now re-open all licenses for the snapshots (it was restricted for outside users).

**Comment by elondaits** [comment]
I closed the issue when I commited the change, but before it was deployed. First I had to test it in staging, but now it's deployed in production and you should be able to see the licenses.
