### ISSUE TITLE
empty sections shown

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#84]
Below each event, the 'Files'-section and the 'Related exhibits' section is shown, even if it is empty.
Empty 'Files'-section also shows below galleries, maybe in other places, too.
![1](https://cloud.githubusercontent.com/assets/10153723/8103298/a99ae102-1027-11e5-8a29-af35c17af396.jpg)

**Comment by HexeBianca** [comment]
'This film is part of'-box is shown, even when empty, as well.
![1](https://cloud.githubusercontent.com/assets/10153723/8103372/37b7e386-1028-11e5-8375-42847f78caee.jpg)

**Comment by christophknoth** [comment]
I am looking into it. Please always add links to your bug reports.

**Comment by HexeBianca** [comment]
It happens for every event and every film.
Here are example links:
http://imaginary.org/event/world-festival-of-animated-film-animafest-zagreb
http://imaginary.org/film/katzengold
