### ISSUE TITLE
landing page galleries

### ISSUE THREAD

**Issue by HexeBianca** [IMAGINARY/imaginary-web#90]
The landing page galleries should be hidden and not come up as suggestion for 'More Galleries'.
![1](https://cloud.githubusercontent.com/assets/10153723/8349605/80c3a532-1b1e-11e5-9b90-601f30783485.jpg)
I don't add a link here, because the selection changes everytime it is loaded.

**Comment by christophknoth** [comment]
I fixed this. But we could also just delete them or not?

**Comment by andreasdanielmatt** [comment]
ok, lets close this, since it is fixed. We will delete or clean up "not necessary galleries or other items" in a different task (we should store the images somewhere then).
