### ISSUE TITLE
films shown as related program

### ISSUE THREAD

**Issue by porst17** [IMAGINARY/imaginary-web#91]
If you select a film as related content for a program, it is listed in the *related programs* section of the program. See for example http://imaginary.org/program/future-of-glaciers-the-module .

Maybe the label should be renamed to something like *related content* or *related exhibits* because showing films as *related programs* is a bit confusing. Maybe there are similar confusing labels in the other sections (film, galleries, etc.). Didn't check.

**Comment by elondaits** [comment]
Indeed the view has a problem. It's attempting to filter by type=Program (to only show related programs) but the list of related items is built through a Views "Relationship", so the type filter might be actually filtering the left side node (the program being displayed, not the related ones).

**Comment by konrad-renner** [comment]
Title for this view is changed from Related Programs to Related Exhibits, which makes more sense in general.
@andreasdanielmatt translation has to be done.

**Comment by elondaits** [comment]
I'll see if we have the translation already. If not, I have a request for translations ready for next week when Bianca is back, and in that case I'll add it there.

**Comment by andreasdanielmatt** [comment]
ok, perfect, so I leave it to you and Bianca (together with other words to be translated, like #34, etc.)

**Comment by elondaits** [comment]
There already was a translation for Related Exhibits, so I made the change. See example:

http://imaginary.org/program/future-of-glaciers-the-module
