### ISSUE TITLE
Redirect Loop in Uruguay event page

### ISSUE THREAD

**Issue by elondaits** [IMAGINARY/imaginary-web#97]
When opening

http://imaginary.org/event/imaginary-uruguay-un-viaje-por-la-matematica

the system informs of a redirect loop.

**Comment by andreasdanielmatt** [comment]
good point. How can we avoid this? I think we have a mess connected to the English translation (which is still in Spanish) of the IMAGINARY Uruguay event site. I added a redirection from imaginary.org/uruguay to the Spanish page (maybe this caused the problem?).

**Comment by elondaits** [comment]
It's fixed now.

The problem was that:
- There was an URL redirect from **event/imaginary-uruguay-un-viaje-por-la-matematica** to **node/892**
- The auto-path generated by the event itself was also **event/imaginary-uruguay-un-viaje-por-la-matematica**

so, when accessing http://imaginary.org/event/imaginary-uruguay-un-viaje-por-la-matematica the following happened:

0. The URL redirect module redirected to node/892
0. The node itself, when opened, redirects to its canonical URL generated by authopath, which is event/imaginary-uruguay-un-viaje-por-la-matematica
0. Go back to 1.

Creating URL redirects is a bit dangerous because of things like this. To avoid problems one has to make sure that the redirect doesn't duplicate any existing URL, as it can replace it / block it or generate this kind of loops.

In this case to solve it I just removed the URL redirect, as it wasn't needed because the auto-path was identical and enough.
