### ISSUE TITLE
make "opening hours" part of "events" translatable

### ISSUE THREAD

**Issue by andreasdanielmatt** [IMAGINARY/imaginary-web#99]
In the venue tab of events there is a free text field called "Opening Hours" in the Time/Place tab. This field is not yet translatable. It would be nice to do so, for example at the IMAGINARY Uruguay exhibition:
http://imaginary.org/es/node/892/edit
(it says "Lunes" in Spanish (which would be Monday in English), etc.)

**Comment by elondaits** [comment]
Created a database backup previous to applying this change:

imaginary_production_2015-09-18_18:18:20.sql.gz

**Comment by elondaits** [comment]
It's done.
No changes to code were needed, just enabling the translation of the field through the UI... but I did testing with existing and new events to see if it behaved and it worked OK.
After enabling on the production server I translated the field in the Uruguay event as a final test.
